#!/bin/zsh

# you can add some directories, just separate them with spaces
workspace_dirs=(/Users/kdisneur/Workspace) 
project=$1;
project_style=${2:-"rails3"}

project_dir=$(find ${workspace_dirs} -iname ${project} -type d -maxdepth 1 | head -n1)

if [ -z ${project} ]; then
  echo "project name is mandatory!";
  exit 1;
fi

tmux has-session -t ${project} 2>-;
if [ $? = 0 ]; then
  tmux attach -t ${project};
  exit 0;
fi

$(dirname ${0})/tmux-files/tmux-${project_style} ${project} ${project_dir}
